version: 2
jobs:
  build:
    docker:
      - image: centos:centos7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run: ./build-remote.sh 315
