version: 2
jobs:
  build:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: build-remote.sh
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: build-remote.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
