version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: cd project; build-remote.sh 315
  test:
    docker:
            - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: cd project; build-remote.sh 315
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
