version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              curl bash py-pip docker      
      - run: ./build-remote.sh 315
