apiVersion: v1
kind: ConfigMap
metadata:
  name: td-config
data:
  NEW_FEATURE: "true"

---
apiVersion: v1
kind: Deployment
metadata:
  name: presto-coordinator
  labels:
    app: presto
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: presto
    spec:
      containers:
      - image: gcr.io/kaggle-218610/presto_jdk8
        resources:
          requests:
            memory: "4.5Gi"
            cpu: "1.5"
          limits:
            memory: "5.0Gi"
            cpu: "2.0"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        name: presto-coordinator
        ports:
        - containerPort: 8080
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: presto-svc
spec:
  selector:
    app: presto
  type: ClusterIP  
  #type: LoadBalancer
  #sessionAffinity: ClientIP
  ports: 
    - port: 8080

