apiVersion: v1
kind: ConfigMap
metadata:
  name: td-config
data:
  NEW_FEATURE: "true"

---

kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: coordinator
  labels:
    presto: coordinator
spec:
  replicas: 2
  template:
    metadata:
      labels:
        presto: coordinator
    spec:
      containers:
      - env:
        - name: PRESTO_JVM_HEAP_SIZE
          value: "4"
        image: gcr.io/kaggle-218610/presto_jdk8
        resources:
          requests:
            memory: "4.5Gi"
            cpu: "1.5"
          limits:
            memory: "5.0Gi"
            cpu: "2.0"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        name: presto-coordinator
        ports:
        - containerPort: 8080
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: presto
  labels:
    app: presto
spec:
  selector:
    presto: coordinator
  ports: 
  - port: 8080


