apiVersion: v1
kind: ConfigMap
metadata:
  name: td-config
data:
  NEW_FEATURE: "true"

---

kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: coordinator
  labels:
    presto: coordinator
spec:
  selector:
    matchLabels:
      presto: coordinator
  template:
    metadata:
      labels:
        presto: coordinator
    spec:
      containers:
      - image: gcr.io/kaggle-218610/presto_jdk8
        resources:
          requests:
            memory: "4.5Gi"
            cpu: "1.5"
          limits:
            memory: "5.0Gi"
            cpu: "2.0"
        readinessProbe:
          exec:
            command:
            - java -jar /usr/bin/presto --execute 'select 1'
          initialDelaySeconds: 2
          periodSeconds: 2
          timeoutSeconds: 60
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        name: presto-coordinator
        ports:
        - containerPort: 8080
      restartPolicy: Always

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: presto-auto-scaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: coordinator
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50

---

apiVersion: v1
kind: Service
metadata:
  name: presto
  labels:
    app: presto
spec:
  selector:
    presto: coordinator
  ports: 
  - port: 8080


